spring:
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    close-timeout: true
    user: admin
    password: admin
    packages:
      trusted: com.broker.activemq.entities,java.lang

application:
  name: CRD-JMS-Adaptor
  in:
    queue: frk.in.queue
  out:
    queue: frk.out.queue
