crd:
  db:
    dir: ${user.home}/crd/${environment}/db
spring:
  jpa:
    show-sql: false
    database-platform: com.frk.crd.db.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
      dialect: com.frk.crd.db.dialect.SQLiteDialect
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        dialect: com.frk.crd.db.dialect.SQLiteDialect
        jdbc:
          batch_size: 1000
        order_inserts: true
        order_updates: true
        generate_statistics: true
    datasource:
      url: jdbc:sqlite:${crd.db.dir}/crd.db
      driver-class-name: org.sqlite.JDBC
      username: sa
      password: sa
      hikari:
        data-source-properties:
          cache_size: 4096
        maximum-pool-size: 64
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    close-timeout: true
    user: admin
    password: admin
    packages:
      trusted: com.broker.activemq.entities,java.lang
  web:
    locale: en_US
  application:
    name: CRD-JMS-Adaptor
  codec:
    max-in-memory-size: 40MB

application:
  name: CRD-JMS-Adaptor
  in:
    queue: frk.in.queue
  out:
    queue: frk.out.queue
---
#Local Environment
environment: local
spring:
  config:
    activate:
      on-profile: local, default
    name: local
server:
  port: 6010