crd:
  app:
    full-path: ${user.home}/adapters
spring:
  application:
    name: CRD-DB-SYNC
  sql:
    init:
      mode: always
      data-locations: classpath:db-script.sql
  h2:
    console:
      enabled: true
      settings:
        trace: true
        web-admin-password: admin
        web-allow-others: true
      path: /h2-console
  datasource:
    username: admin
    password: admin
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:~/crd-h2-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;MODE=ORACLE;
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
logging:
  file:
    path: ${crd.app.full-path}/logs/${environment}
server:
  port: 6010
---
#Local Default Environment
#Local Environment
environment: local
spring:
  config:
    activate:
      on-profile: local, default
    name: local
---
#Development Environment 2
environment: dev2
spring:
  config:
    activate:
      on-profile: dev2
    name: dev2
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.OracleDialect
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=crimsdevdb-scan.corp.frk.com)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=CRDDEVC2)))
    driver-class-name: oracle.jdbc.OracleDriver
    username: vayyala
    password: Weclome#321
server:
  port: 7010
