environment: dev
server:
  port: 9040
ibm:
  mq:
    queueManager: MWDEV01A
    channel: MWDEV01.A.CLNTCONN
    host: rcovlnx3203
    port: 1420
    connName: rcovlnx3203(1420)
crd:
  app:
    in:
      queue: QLD.CRI.TIS.ORD.REQUEST.Q12
    out:
      queue: QLD.CRI.TIS.ORD.REQUEST.Q11
spring:
  application:
    name: crd-pmd-wf-rule-processor-app
---
#Local Environment
environment: local
server:
  port: 6040
logging:
  file:
    path: ${crd.app.full-path}/${environment}/logs
spring:
  config:
    activate:
      on-profile: local, default
    name: local
  activemq:
    brokerUrl: tcp://localhost:61616
    inMemory: true
    closeTimeout: true
    user: admin
    password: admin
    packages:
      trusted: com.broker.activemq.entities,java.lang
crd:
  app:
    full-path: ${user.home}/adapters/${spring.application.name}
---
#Development Environment
environment: dev
spring:
  config:
    activate:
      on-profile: dev
    name: dev
server:
  port: 7040
---
#UAT Environment
environment: uat
spring:
  config:
    activate:
      on-profile: uat
    name: uat
server:
  port: 8040
---
#Production Environment
environment: prod
spring:
  config:
    activate:
      on-profile: prod
    name: prod
