crd:
  app:
    pmd:
      in:
        queue: QLD.CRI.TIS.ORD.REQUEST.Q12
      forward:
        queue: QLD.CRI.TIS.ORD.REQUEST.pmd.forward.queue
    chub:
      in:
        queue: QLD.CRI.TIS.ORD.REQUEST.Q13
      forward:
        queue: QLD.CRI.TIS.ORD.REQUEST.chub.forward.queue
    full-path: ${user.home}/adapters/${spring.application.name}
    message:
      folder: ${crd.app.full-path}/messages/
camel:
  component:
    jms:
      acknowledgement-mode-name: AUTO_ACKNOWLEDGE
#Spring Properties
spring:
  application:
    name: CRD-PMD-WF-RULE-PROCESSOR-APP
  web:
    locale: en_US
  main:
    banner-mode: off
#Logging Properties
logging:
  file:
    path: ${crd.app.full-path}/logs
---
#ActiveMQ Environment
spring:
  config:
    activate:
      on-profile: activemq
    name: activemq
  activemq:
    brokerUrl: tcp://localhost:61616
    inMemory: true
    packages:
      truested: com.broker.activemq.entities,java.lang
    pool:
      enabled: true
      max-connections: 10
      max-sessions-per-connection: 10
    user: admin
    password: admin
---
#IBMMQ Environment
spring:
  config:
    activate:
      on-profile: ibmmq
    name: ibmmq
ibm:
  mq:
    queueManager: MWDEV01A
    channel: MWDEV01.A.CLNTCONN
    host: rcovlnx3203
    port: 1420
    connName: rcovlnx3203(1420)
---
#Local Environment
environment: local
spring:
  config:
    activate:
      on-profile: local, default
    name: local
server:
  port: 6040
---
#Development Environment 2
environment: dev2
spring:
  config:
    activate:
      on-profile: dev2
    name: dev2
server:
  port: 7040
crd:
  app:
    full-path: /apps/crd.dev2/adapters/crd-pmd-workflow-rule-processor-local
---
#Development Environment
environment: dev
spring:
  config:
    activate:
      on-profile: dev
    name: dev
server:
  port: 7040
---
#UAT Environment
environment: uat
spring:
  config:
    activate:
      on-profile: uat
    name: uat
server:
  port: 8040
---
#Production Environment
environment: prod
spring:
  config:
    activate:
      on-profile: prod
    name: prod
