server:
  port: 9030
crd:
  app:
    db:
      service:
        url: http://localhost:6010
    pmd:
      in:
        queue: QLD.CRI.TIS.ORD.REQUEST.Q12
      out:
        queue: QLD.CRI.TIS.ORD.REQUEST.Q12
    chub:
      in:
        queue: QLD.CRI.TIS.ORD.REQUEST.Q13
      out:
        queue: QLD.CRI.TIS.ORD.REQUEST.Q13
    full-path: /apps/crd.dev2/adapters/crd-pmd-event-processor-local
    message:
      folder: ${crd.app.full-path}/messages
spring:
  application:
    name: CRD-PMD-EVENT-PROCESSOR-APP
logging:
  file:
    path: ${crd.app.full-path}/logs
---
#ActiveMQ Environment
environment: activemq
spring:
  config:
    activate:
      on-profile: activemq
    name: activemq
  activemq:
    brokerUrl: tcp://localhost:61616
    inMemory: true
    user: admin
    password: admin
    packages:
      trusted: com.broker.activemq.entities,java.lang
---
#IBMMQ Environment
environment: ibmmq
spring:
  config:
    activate:
      on-profile: ibmmq
    name: ibmmq
ibm:
  mq:
    queueManager: MWDEV01A
    channel: MWDEV01.A.CLNTCONN
    host: rcovlnx3203
    port: 1420
    connName: rcovlnx3203(1420)
---
#Local Environment
environment: local
server:
  port: 6030
spring:
  config:
    activate:
      on-profile: local, default
    name: local
crd:
  app:
    db:
      service:
        url: http://localhost:6010
    full-path: /apps/crd.dev2/adapters/crd-pmd-event-processor-local
---
#Development Environment
environment: dev
spring:
  config:
    activate:
      on-profile: dev
    name: dev
server:
  port: 7030
---
#Development Environment
environment: dev2
spring:
  config:
    activate:
      on-profile: dev2
    name: dev2
server:
  port: 7030
crd:
  app:
    db:
      service:
        url: http://localhost:7010
    full-path: /apps/crd.dev2/adapters/crd-pmd-workflow-rule-processor-local
    message:
      folder: ${crd.app.full-path}/messages
---
#UAT Environment
environment: uat
spring:
  config:
    activate:
      on-profile: uat
    name: uat
server:
  port: 8030
---
#Production Environment
environment: prod
spring:
  config:
    activate:
      on-profile: prod
    name: prod
