server:
  port: 9030
crd:
  app:
    db:
      service:
        url: http://localhost:6010
    pmd:
      in:
        queue: QLD.CRI.TIS.ORD.REQUEST.pmd.forward.queue
      out:
        queue: QLD.CRI.TIS.ORD.REQUEST.pmd.out.queue
    chub:
      in:
        queue: QLD.CRI.TIS.ORD.REQUEST.chub.forward.queue
      out:
        queue: QLD.CRI.TIS.ORD.REQUEST.chub.out.queue
    full-path: ${user.home}/adapters/${spring.application.name}
spring:
  application:
    name: CRD-PMD-EVENT-PROCESSOR-APP
logging:
  file:
    path: ${crd.app.full-path}/${environment}/logs
---
#ActiveMQ Environment
environment: activemq
spring:
  config:
    activate:
      on-profile: activemq
    name: activemq
  activemq:
    brokerUrl: tcp://localhost:61616
    inMemory: true
    user: admin
    password: admin
    packages:
      trusted: com.broker.activemq.entities,java.lang
---
#IBMMQ Environment
environment: ibmmq
spring:
  config:
    activate:
      on-profile: ibmmq
    name: ibmmq
ibm:
  mq:
    queueManager: MWDEV01A
    channel: MWDEV01.A.CLNTCONN
    host: rcovlnx3203
    port: 1420
    connName: rcovlnx3203(1420)
---
#Local Environment
environment: local
server:
  port: 6030
spring:
  config:
    activate:
      on-profile: local, default
    name: local
---
#Development Environment
environment: dev
spring:
  config:
    activate:
      on-profile: dev
    name: dev
server:
  port: 7030
---
#UAT Environment
environment: uat
spring:
  config:
    activate:
      on-profile: uat
    name: uat
server:
  port: 8030
---
#Production Environment
environment: prod
spring:
  config:
    activate:
      on-profile: prod
    name: prod
